/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mybyteman_MoodyCamelBuffer */

#ifndef _Included_org_mybyteman_MoodyCamelBuffer
#define _Included_org_mybyteman_MoodyCamelBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mybyteman_MoodyCamelBuffer
 * Method:    put
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_mybyteman_MoodyCamelBuffer_put
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mybyteman_MoodyCamelBuffer
 * Method:    printAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mybyteman_MoodyCamelBuffer_printAll
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
